// apps/react-web/src/components/Navigation/SidebarNav.tsx
import React from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../../app/providers/AuthProvider';
import './SidebarNav.css';

const SidebarNav: React.FC = () => {
  const { signOut } = useAuth();
  const navigate = useNavigate();

  const handleLogout = () => {
    signOut();
    navigate('/landing');
  };

  return (
    <div className="sidebar">
      <div className="sidebar-header">
        <div className="logo">
          <span className="logo-icon">⚡</span>
          <span className="logo-text">ApexFlow</span>
        </div>
      </div>
      
      <nav className="sidebar-nav">
        <div className="nav-section">
          <div className="nav-section-title">Main</div>
          <NavLink to="/dashboard" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
            <span className="nav-icon">📊</span>
            <span className="nav-text">Dashboard</span>
          </NavLink>
          <NavLink to="/upload" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
            <span className="nav-icon">📤</span>
            <span className="nav-text">Upload</span>
          </NavLink>
          <NavLink to="/documents" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
            <span className="nav-icon">📄</span>
            <span className="nav-text">Documents</span>
          </NavLink>
        </div>
        
        <div className="nav-section">
          <div className="nav-section-title">AI Tools</div>
          <NavLink to="/workflows" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
            <span className="nav-icon">🔄</span>
            <span className="nav-text">Workflows</span>
          </NavLink>
          <NavLink to="/ai-assistant" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
            <span className="nav-icon">🤖</span>
            <span className="nav-text">AI Assistant</span>
          </NavLink>
        </div>
        
        <div className="nav-section">
          <div className="nav-section-title">Settings</div>
          <NavLink to="/integrations" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
            <span className="nav-icon">🔌</span>
            <span className="nav-text">Integrations</span>
          </NavLink>
          <NavLink to="/profile" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
            <span className="nav-icon">👤</span>
            <span className="nav-text">Profile</span>
          </NavLink>
        </div>
      </nav>
      
      <div className="sidebar-footer">
        <button className="logout-btn" onClick={handleLogout}>
          <span className="nav-icon">🚪</span>
          <span className="nav-text">Sign Out</span>
        </button>
      </div>
    </div>
  );
};

export default SidebarNav;

// apps/angular-web/src/app/components/sidebar-nav/sidebar-nav.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-sidebar-nav',
  standalone: true,
  imports: [CommonModule, RouterModule],
  styleUrls: ['./sidebar-nav.component.css'],
  template: `
    <div class="sidebar">
      <div class="sidebar-header">
        <div class="logo">
          <span class="logo-icon">⚡</span>
          <span class="logo-text">ApexFlow</span>
        </div>
      </div>
      
      <nav class="sidebar-nav">
        <div class="nav-section">
          <div class="nav-section-title">Main</div>
          <a routerLink="/dashboard" routerLinkActive="active" class="nav-item">
            <span class="nav-icon">📊</span>
            <span class="nav-text">Dashboard</span>
          </a>
          <a routerLink="/upload" routerLinkActive="active" class="nav-item">
            <span class="nav-icon">📤</span>
            <span class="nav-text">Upload</span>
          </a>
          <a routerLink="/documents" routerLinkActive="active" class="nav-item">
            <span class="nav-icon">📄</span>
            <span class="nav-text">Documents</span>
          </a>
        </div>
        
        <div class="nav-section">
          <div class="nav-section-title">AI Tools</div>
          <a routerLink="/workflows" routerLinkActive="active" class="nav-item">
            <span class="nav-icon">🔄</span>
            <span class="nav-text">Workflows</span>
          </a>
          <a routerLink="/search" routerLinkActive="active" class="nav-item">
            <span class="nav-icon">🔍</span>
            <span class="nav-text">Search</span>
          </a>
          <a routerLink="/chat" routerLinkActive="active" class="nav-item">
            <span class="nav-icon">💬</span>
            <span class="nav-text">Document Chat</span>
          </a>
        </div>
        
        <div class="nav-section">
          <div class="nav-section-title">Settings</div>
          <a routerLink="/integrations" routerLinkActive="active" class="nav-item">
            <span class="nav-icon">🔌</span>
            <span class="nav-text">Integrations</span>
          </a>
          <a routerLink="/profile" routerLinkActive="active" class="nav-item">
            <span class="nav-icon">👤</span>
            <span class="nav-text">Profile</span>
          </a>
        </div>
      </nav>
      
      <div class="sidebar-footer">
        <button class="logout-btn" (click)="logout()">
          <span class="nav-icon">🚪</span>
          <span class="nav-text">Sign Out</span>
        </button>
      </div>
    </div>
  `
})
export class SidebarNavComponent {
  constructor(private authService: AuthService, private router: Router) {}

  logout(): void {
    this.authService.signOut();
    this.router.navigate(['/landing']);
  }
}
