// apps/angular-web/src/app/components/auth-modal/auth-modal.component.ts
import { Component, EventEmitter, Input, Output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-auth-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  styleUrls: ['./auth-modal.component.css'],
  template: `
    <div class="modal-overlay" [class.visible]="isVisible" (click)="onOverlayClick($event)">
      <div class="modal-content" (click)="$event.stopPropagation()">
        <div class="modal-header">
          <h2>{{ isSignUp() ? 'Create Account' : 'Welcome Back' }}</h2>
          <button class="close-btn" (click)="onClose()">&times;</button>
        </div>

        <div class="modal-body">
          <!-- Google Sign In Button -->
          <button 
            class="btn btn-google" 
            (click)="onGoogleSignIn()"
            [disabled]="isLoading()"
          >
            <svg width="20" height="20" viewBox="0 0 24 24">
              <path fill="#4285f4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
              <path fill="#34a853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
              <path fill="#fbbc05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
              <path fill="#ea4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
            </svg>
            {{ isLoading() ? 'Please wait...' : 'Continue with Google' }}
          </button>

          <div class="divider">
            <span>or</span>
          </div>

          <!-- Email/Password Form -->
          <form (ngSubmit)="onSubmit()" #authForm="ngForm">
            <div class="form-group" *ngIf="isSignUp()">
              <label for="name">Full Name</label>
              <input 
                type="text" 
                id="name" 
                name="name"
                [(ngModel)]="formData.name" 
                required
                placeholder="Enter your full name"
              />
            </div>

            <div class="form-group">
              <label for="email">Email</label>
              <input 
                type="email" 
                id="email" 
                name="email"
                [(ngModel)]="formData.email" 
                required
                placeholder="Enter your email"
              />
            </div>

            <div class="form-group">
              <label for="password">Password</label>
              <input 
                type="password" 
                id="password" 
                name="password"
                [(ngModel)]="formData.password" 
                required
                placeholder="Enter your password"
                minlength="6"
              />
            </div>

            <div class="form-group" *ngIf="isSignUp()">
              <label for="confirmPassword">Confirm Password</label>
              <input 
                type="password" 
                id="confirmPassword" 
                name="confirmPassword"
                [(ngModel)]="formData.confirmPassword" 
                required
                placeholder="Confirm your password"
                minlength="6"
              />
            </div>

            <div class="error-message" *ngIf="errorMessage()">
              {{ errorMessage() }}
            </div>

            <button 
              type="submit" 
              class="btn btn-primary btn-full"
              [disabled]="isLoading() || !authForm.form.valid"
            >
              {{ isLoading() ? 'Please wait...' : (isSignUp() ? 'Create Account' : 'Sign In') }}
            </button>
          </form>

          <div class="switch-mode">
            <span>{{ isSignUp() ? 'Already have an account?' : "Don't have an account?" }}</span>
            <button type="button" class="link-btn" (click)="toggleMode()">
              {{ isSignUp() ? 'Sign In' : 'Sign Up' }}
            </button>
          </div>
        </div>
      </div>
    </div>
  `
})
export class AuthModalComponent {
  @Input() isVisible = false;
  @Output() close = new EventEmitter<void>();
  @Output() authenticated = new EventEmitter<void>();

  private signUpMode = signal(false);
  private loading = signal(false);
  private error = signal('');

  formData = {
    name: '',
    email: '',
    password: '',
    confirmPassword: ''
  };

  constructor(private authService: AuthService) {}

  isSignUp = this.signUpMode.asReadonly();
  isLoading = this.loading.asReadonly();
  errorMessage = this.error.asReadonly();

  onOverlayClick(event: Event): void {
    if (event.target === event.currentTarget) {
      this.onClose();
    }
  }

  onClose(): void {
    this.close.emit();
    this.resetForm();
  }

  toggleMode(): void {
    this.signUpMode.update(mode => !mode);
    this.error.set('');
  }

  async onGoogleSignIn(): Promise<void> {
    this.loading.set(true);
    this.error.set('');

    try {
      const success = await this.authService.signInWithGoogle();
      if (success) {
        this.authenticated.emit();
        this.onClose();
      } else {
        this.error.set('Google sign in failed. Please try again.');
      }
    } catch (error) {
      this.error.set('Google sign in failed. Please try again.');
    } finally {
      this.loading.set(false);
    }
  }

  async onSubmit(): Promise<void> {
    if (this.isSignUp() && this.formData.password !== this.formData.confirmPassword) {
      this.error.set('Passwords do not match.');
      return;
    }

    this.loading.set(true);
    this.error.set('');

    try {
      let success = false;

      if (this.isSignUp()) {
        success = await this.authService.signUpWithEmail(
          this.formData.email,
          this.formData.password,
          this.formData.name
        );
      } else {
        success = await this.authService.signInWithEmail(
          this.formData.email,
          this.formData.password
        );
      }

      if (success) {
        this.authenticated.emit();
        this.onClose();
      } else {
        this.error.set(
          this.isSignUp() 
            ? 'Account creation failed. Please try again.' 
            : 'Invalid email or password.'
        );
      }
    } catch (error) {
      this.error.set('An error occurred. Please try again.');
    } finally {
      this.loading.set(false);
    }
  }

  private resetForm(): void {
    this.formData = {
      name: '',
      email: '',
      password: '',
      confirmPassword: ''
    };
    this.error.set('');
    this.loading.set(false);
    this.signUpMode.set(false);
  }
}

// apps/react-web/src/features/auth/components/AuthModal.tsx
import React, { useState } from 'react';
import { useAuth } from '../../../app/providers/AuthProvider';
import Button from '../../../components/atoms/Button/Button';
import Input from '../../../components/atoms/Input/Input';
import './AuthModal.css';

interface AuthModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAuthenticated: () => void;
}

const AuthModal: React.FC<AuthModalProps> = ({ isOpen, onClose, onAuthenticated }) => {
  const [isSignIn, setIsSignIn] = useState(true);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const { signInWithEmail, signUpWithEmail, signInWithGoogle } = useAuth();

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');

    try {
      let success: boolean;
      if (isSignIn) {
        success = await signInWithEmail(email, password);
      } else {
        success = await signUpWithEmail(email, password, name);
      }

      if (success) {
        onAuthenticated();
      } else {
        setError('Authentication failed. Please try again.');
      }
    } catch (err) {
      console.error('Authentication error:', err);
      setError('An error occurred. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGoogleAuth = async () => {
    setIsLoading(true);
    setError('');

    try {
      const success = await signInWithGoogle();
      if (success) {
        onAuthenticated();
      } else {
        setError('Google authentication failed. Please try again.');
      }
    } catch (err) {
      console.error('Google authentication error:', err);
      setError('An error occurred with Google authentication.');
    } finally {
      setIsLoading(false);
    }
  };

  const resetForm = () => {
    setEmail('');
    setPassword('');
    setName('');
    setError('');
    setIsLoading(false);
  };

  const toggleMode = () => {
    setIsSignIn(!isSignIn);
    resetForm();
  };

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  return (
    <div className="modal-backdrop" onClick={handleBackdropClick}>
      <div className="modal-content auth-modal">
        <div className="modal-header">
          <h2>{isSignIn ? 'Welcome back' : 'Create your account'}</h2>
          <button className="close-btn" onClick={onClose}>×</button>
        </div>

        <div className="modal-body">
          {error && (
            <div className="error-message">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit}>
            {!isSignIn && (
              <Input
                type="text"
                label="Full Name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
                disabled={isLoading}
              />
            )}

            <Input
              type="email"
              label="Email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              disabled={isLoading}
            />

            <Input
              type="password"
              label="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              disabled={isLoading}
            />

            <Button 
              type="submit" 
              variant="primary"
              fullWidth
              loading={isLoading}
            >
              {isSignIn ? 'Sign In' : 'Create Account'}
            </Button>
          </form>

          <div className="divider">
            <span>or</span>
          </div>

          <button 
            className="google-signin-btn"
            onClick={handleGoogleAuth}
            disabled={isLoading}
          >
            <div className="google-icon">
              {isLoading ? (
                <div className="google-loading-spinner"></div>
              ) : (
                <svg width="18" height="18" viewBox="0 0 18 18">
                  <path fill="#4285F4" d="M9 3.48c1.69 0 2.83.73 3.48 1.34l2.54-2.48C13.46.89 11.43 0 9 0 5.48 0 2.44 2.02.96 4.96l2.91 2.26C4.6 5.05 6.62 3.48 9 3.48z"/>
                  <path fill="#34A853" d="M17.64 9.2c0-.74-.06-1.28-.19-1.84H9v3.34h4.96c-.1.83-.64 2.08-1.84 2.98l2.84 2.2c1.7-1.57 2.68-3.88 2.68-6.68z"/>
                  <path fill="#FBBC05" d="M3.88 10.78A5.54 5.54 0 0 1 3.58 9c0-.62.11-1.22.29-1.78L.96 4.96A9.008 9.008 0 0 0 0 9c0 1.45.35 2.82.96 4.04l2.92-2.26z"/>
                  <path fill="#EA4335" d="M9 18c2.43 0 4.47-.8 5.96-2.18l-2.84-2.2c-.76.53-1.78.9-3.12.9-2.38 0-4.4-1.57-5.12-3.74L.96 13.04C2.45 15.98 5.48 18 9 18z"/>
                </svg>
              )}
            </div>
            <span className="google-text">
              {isLoading ? 'Signing in...' : 'Continue with Google'}
            </span>
          </button>

          <div className="auth-toggle">
            {isSignIn ? (
              <p>
                Don't have an account?{' '}
                <button type="button" onClick={toggleMode} className="link-btn">
                  Sign up
                </button>
              </p>
            ) : (
              <p>
                Already have an account?{' '}
                <button type="button" onClick={toggleMode} className="link-btn">
                  Sign in
                </button>
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AuthModal;
